application: twitter-data-dump
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: app.application
  
libraries:
- name: pycrypto
  version: latest

- name: ssl
  version: latest
  